import os
from yacs.config import CfgNode as CN

_C = CN()
_C.VERSION = 2

_C.DISTRIBUTED = False

# model
_C.MODEL = CN()
_C.MODEL.META_ARCHITECTURE = "resnet18"
_C.MODEL.NUM_CLASS = 4
_C.MODEL.WEIGHT = None
_C.MODEL.BATCH_SIZE = 1
_C.MODEL.WORKERS = 1

# dataset
_C.DATASET = CN()
_C.DATASET.ROOT_PATH = ""
_C.DATASET.DATASET_NAME = "VOC"
_C.DATASET.TRANSFORM_NAME = "generalized_transform"
_C.DATASET.SAMPLER = "random_sampler"
_C.DATASET.MEAN = [102.9801, 115.9465, 122.7717]
_C.DATASET.STD = [1.0, 1.0, 1.0]
_C.DATASET.RESIZE_SHAPE = [128, 128]
_C.DATASET.CROP_SHAPE = [120, 120]
_C.DATASET.TRAIN_FILE = None
_C.DATASET.VAL_FILE = None

# solver
_C.SOLVER = CN()
_C.SOLVER.LOSS_NAME = 'cross_entropy_loss'
_C.SOLVER.OPTIMIZER = 'sgd'
_C.SOLVER.SCHEDULER = 'step_lr'
_C.SOLVER.BASE_LR = 0.1
_C.SOLVER.MOMENTUM = 0.9
_C.SOLVER.WEIGHT_DECAY = 0.0005
_C.SOLVER.STEP_SIZE = 1
_C.SOLVER.MAX_EPOCH = 100
_C.SOLVER.T_MAX = 10

# output
_C.OUTPUT = CN()
_C.OUTPUT.WORK_DIR = ""
